# Docker Compose override for development
# This file is automatically loaded by docker-compose and provides development-specific configurations

version: '3.8'

services:
  backend:
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  postgres:
    ports:
      - "5432:5432"  # Expose postgres port for development tools

# Development-specific volumes
volumes:
  postgres_data:
  nginx_ssl:
